version: '3.9'

services:
  auth_service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    env_file:
      - auth-service/.env.dev
    volumes:
      - ./auth-service/db:/app/db
  products_service:
    build:
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    depends_on:
      - auth_service
    links:
      - auth_service:auth_service
    env_file:
      - products-service/.env.dev
    volumes:
      - ./products-service/db:/app/db
  shopping_service:
    build:
      context: ./shopping-service
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    depends_on:
      - auth_service
      - products_service
    links:
      - auth_service:auth_service
      - products_service:products_service
    env_file:
      - shopping-service/.env.dev
    volumes:
      - ./shopping-service/db:/app/db
